# Generated by Django 3.1.7 on 2024-01-27 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('clabe', models.CharField(max_length=100)),
                ('paid_card', models.BooleanField(default=False)),
                ('card_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertiesCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('transmitter', models.CharField(choices=[('Sucursal', 'Sucursal'), ('Línea', 'Línea')], max_length=100, null=True)),
                ('type', models.CharField(choices=[('Física', 'Física'), ('Digital', 'Digital')], max_length=100, null=True)),
                ('expiration_active', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('restriction', models.BooleanField(default=False, null=True)),
                ('multiple_use', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'verbose_name': 'PropertiesCard',
                'verbose_name_plural': 'PropertiesCards',
                'ordering': ('-created_at',),
            },
        ),
    ]
