# Generated by Django 3.1.7 on 2024-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='paid_card',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
